"""Stable public SDK for OmniTensor workload plugin packages."""

from ..plugins.artifacts import ArtifactReference, ArtifactResolution
from ..plugins.pipeline import (
    CollectedOutput,
    DeliveredOutput,
    InferenceOutput,
    PostprocessedOutput,
    PreprocessedOutput,
)
from ..plugins.protocol import (
    CancellationToken,
    JsonObject,
    JsonValue,
    PluginContext,
    PluginHealth,
    PluginHealthStatus,
    PluginProgress,
    PluginRequest,
    PluginResult,
    PluginResultStatus,
    ProgressReporter,
    WorkloadPlugin,
)
from ..plugins.settings import ConfigurationMigration, PluginConfigurationSpec
from ..plugins.triggers import Collector, CollectorReadiness, SourceStatus, Trigger, TriggerKind
from .base import ManagedPlugin
from .contracts import ArtifactProvider, PipelineHooks, ProgressSink, ResultSink
from .helpers import (
    MAX_PROGRESS_DETAIL_CHARS,
    MAX_PROGRESS_STAGE_CHARS,
    MAX_RESULT_DETAIL_CHARS,
    ArtifactView,
    CancellationController,
    ConfigurationView,
    PermissionView,
    PluginCancelledError,
    ProgressEmitter,
    SDKContractError,
    cancelled_result,
    failed_result,
    succeeded_result,
)

__all__ = [
    "MAX_PROGRESS_DETAIL_CHARS",
    "MAX_PROGRESS_STAGE_CHARS",
    "MAX_RESULT_DETAIL_CHARS",
    "ArtifactProvider",
    "ArtifactReference",
    "ArtifactResolution",
    "ArtifactView",
    "CancellationController",
    "CancellationToken",
    "CollectedOutput",
    "Collector",
    "CollectorReadiness",
    "ConfigurationMigration",
    "ConfigurationView",
    "DeliveredOutput",
    "InferenceOutput",
    "JsonObject",
    "JsonValue",
    "ManagedPlugin",
    "PermissionView",
    "PipelineHooks",
    "PluginCancelledError",
    "PluginConfigurationSpec",
    "PluginContext",
    "PluginHealth",
    "PluginHealthStatus",
    "PluginProgress",
    "PluginRequest",
    "PluginResult",
    "PluginResultStatus",
    "PostprocessedOutput",
    "PreprocessedOutput",
    "ProgressEmitter",
    "ProgressReporter",
    "ProgressSink",
    "ResultSink",
    "SDKContractError",
    "SourceStatus",
    "Trigger",
    "TriggerKind",
    "WorkloadPlugin",
    "cancelled_result",
    "failed_result",
    "succeeded_result",
]
