"""Stable, lazily resolved contracts for workload plugins."""

from __future__ import annotations

from importlib import import_module as _import_module
from threading import local as _local

# Keep this map explicit: importing the barrel must not import every plugin owner.
# Insertion order is the long-standing public export order.
_EXPORTS: dict[str, tuple[str, str]] = {
    "AsyncioSubprocessLauncher": (".supervisor_process", "AsyncioSubprocessLauncher"),
    "AcceleratorRuntime": (".artifact_compatibility", "AcceleratorRuntime"),
    "ArtifactCompatibility": (".artifact_compatibility", "ArtifactCompatibility"),
    "ArtifactCompatibilityChecker": (".artifact_compatibility", "ArtifactCompatibilityChecker"),
    "ArtifactCompatibilityDecision": (".artifact_compatibility", "ArtifactCompatibilityDecision"),
    "ArtifactCache": (".artifact_cache", "ArtifactCache"),
    "ArtifactCacheAccounting": (".artifact_cache", "ArtifactCacheAccounting"),
    "ArtifactCacheCollection": (".artifact_cache", "ArtifactCacheCollection"),
    "ArtifactCacheError": (".artifact_cache", "ArtifactCacheError"),
    "DEFAULT_MAX_ARTIFACT_BYTES": (".artifacts", "DEFAULT_MAX_ARTIFACT_BYTES"),
    "DEFAULT_HANDSHAKE_TIMEOUT_SECONDS": (
        ".supervisor_process",
        "DEFAULT_HANDSHAKE_TIMEOUT_SECONDS",
    ),
    "DEFAULT_MAX_FRAME_BYTES": (".ipc", "DEFAULT_MAX_FRAME_BYTES"),
    "DEFAULT_COLLECTION_TIMEOUT_SECONDS": (".triggers", "DEFAULT_COLLECTION_TIMEOUT_SECONDS"),
    "DEFAULT_AUDIT_EVENTS": (".grants", "DEFAULT_AUDIT_EVENTS"),
    "DEFAULT_MAX_GRANTS_BYTES": (".grants", "DEFAULT_MAX_GRANTS_BYTES"),
    "DEFAULT_MAX_NETWORK_LINKS": (".network_collection", "DEFAULT_MAX_NETWORK_LINKS"),
    "DEFAULT_MAX_PERIPHERAL_DEVICES": (".peripheral_collection", "DEFAULT_MAX_PERIPHERAL_DEVICES"),
    "DEFAULT_MAX_PENDING_TRIGGERS": (".triggers", "DEFAULT_MAX_PENDING_TRIGGERS"),
    "DEFAULT_MAX_SETTINGS_BYTES": (".settings", "DEFAULT_MAX_SETTINGS_BYTES"),
    "DEFAULT_MAX_TRIGGER_BYTES": (".triggers", "DEFAULT_MAX_TRIGGER_BYTES"),
    "DEFAULT_STOP_TIMEOUT_SECONDS": (".supervisor_process", "DEFAULT_STOP_TIMEOUT_SECONDS"),
    "FRAME_FORMAT_VERSION": (".ipc", "FRAME_FORMAT_VERSION"),
    "ArtifactReference": (".artifacts", "ArtifactReference"),
    "ArtifactReadiness": (".telemetry", "ArtifactReadiness"),
    "ArtifactResolution": (".artifacts", "ArtifactResolution"),
    "ArtifactResolver": (".artifacts", "ArtifactResolver"),
    "ActiveGrant": (".grants", "ActiveGrant"),
    "ArtifactActivation": (".artifact_installation", "ArtifactActivation"),
    "ArtifactInstallation": (".artifact_installation", "ArtifactInstallation"),
    "ArtifactInstallationError": (".artifact_installation", "ArtifactInstallationError"),
    "ArtifactInstaller": (".artifact_installation", "ArtifactInstaller"),
    "ArtifactProvenance": (".artifact_trust", "ArtifactProvenance"),
    "ArtifactTrustDecision": (".artifact_trust", "ArtifactTrustDecision"),
    "ArtifactTrustPolicy": (".artifact_trust", "ArtifactTrustPolicy"),
    "ArtifactTrustRoot": (".artifact_trust", "ArtifactTrustRoot"),
    "ArtifactTrustVerifier": (".artifact_trust", "ArtifactTrustVerifier"),
    "ADVISORY_RISK_MAX": (".summaries", "ADVISORY_RISK_MAX"),
    "DEFAULT_CALL_TIMEOUT_SECONDS": (".budgets", "DEFAULT_CALL_TIMEOUT_SECONDS"),
    "DEFAULT_MAX_CONCURRENCY": (".budgets", "DEFAULT_MAX_CONCURRENCY"),
    "DEFAULT_MAX_DESCRIPTORS": (".budgets", "DEFAULT_MAX_DESCRIPTORS"),
    "DEFAULT_MAX_MEMORY_BYTES": (".budgets", "DEFAULT_MAX_MEMORY_BYTES"),
    "DEFAULT_MAX_PROCESSES": (".budgets", "DEFAULT_MAX_PROCESSES"),
    "DEFAULT_MAX_RESTARTS": (".supervisor_recovery", "DEFAULT_MAX_RESTARTS"),
    "DEFAULT_RESTART_BACKOFF_MULTIPLIER": (
        ".supervisor_recovery",
        "DEFAULT_RESTART_BACKOFF_MULTIPLIER",
    ),
    "DEFAULT_RESTART_DECAY_SECONDS": (".supervisor_recovery", "DEFAULT_RESTART_DECAY_SECONDS"),
    "DEFAULT_RESTART_INITIAL_BACKOFF_SECONDS": (
        ".supervisor_recovery",
        "DEFAULT_RESTART_INITIAL_BACKOFF_SECONDS",
    ),
    "DEFAULT_RESTART_MAX_BACKOFF_SECONDS": (
        ".supervisor_recovery",
        "DEFAULT_RESTART_MAX_BACKOFF_SECONDS",
    ),
    "CancellationToken": (".protocol", "CancellationToken"),
    "CollectedOutput": (".pipeline", "CollectedOutput"),
    "CollectionOutcome": (".triggers", "CollectionOutcome"),
    "CollectionPermissionGate": (".collection", "CollectionPermissionGate"),
    "CollectionStatus": (".triggers", "CollectionStatus"),
    "CompatibleArtifactResolver": (".artifact_compatibility", "CompatibleArtifactResolver"),
    "Collector": (".triggers", "Collector"),
    "CollectorReadiness": (".triggers", "CollectorReadiness"),
    "DeliveredOutput": (".pipeline", "DeliveredOutput"),
    "ConfigurationMigration": (".settings", "ConfigurationMigration"),
    "CURRENT_MANIFEST_VERSION": (".manifest_compatibility", "CURRENT_MANIFEST_VERSION"),
    "CURRENT_RUNTIME_API": (".manifest_compatibility", "CURRENT_RUNTIME_API"),
    "DEFAULT_PROTOCOL_CAPABILITIES": (".manifest_compatibility", "DEFAULT_PROTOCOL_CAPABILITIES"),
    "DEFAULT_PROTOCOL_MAXIMUM": (".manifest_compatibility", "DEFAULT_PROTOCOL_MAXIMUM"),
    "DEFAULT_PROTOCOL_MINIMUM": (".manifest_compatibility", "DEFAULT_PROTOCOL_MINIMUM"),
    "HandshakeAgreement": (".ipc", "HandshakeAgreement"),
    "HandshakeOffer": (".ipc", "HandshakeOffer"),
    "GRANTS_DOCUMENT_VERSION": (".grants", "GRANTS_DOCUMENT_VERSION"),
    "GrantAction": (".grants", "GrantAction"),
    "GrantAuditEvent": (".grants", "GrantAuditEvent"),
    "GrantError": (".grants", "GrantError"),
    "GrantLedger": (".grants", "GrantLedger"),
    "GrantOrigin": (".grants", "GrantOrigin"),
    "GrantProvenance": (".grants", "GrantProvenance"),
    "GrantSnapshot": (".grants", "GrantSnapshot"),
    "ConsentGuard": (".revocation", "ConsentGuard"),
    "LiveGrantView": (".revocation", "LiveGrantView"),
    "RevocationError": (".revocation", "RevocationError"),
    "DEFAULT_REVOCATION_POLL_SECONDS": (".revocation", "DEFAULT_REVOCATION_POLL_SECONDS"),
    "MAX_REVOCATION_POLL_SECONDS": (".revocation", "MAX_REVOCATION_POLL_SECONDS"),
    "IPCFrame": (".ipc", "IPCFrame"),
    "IPCProtocolError": (".ipc", "IPCProtocolError"),
    "InstalledPluginRuntime": (".loading", "InstalledPluginRuntime"),
    "InstalledPluginSnapshot": (".loading", "InstalledPluginSnapshot"),
    "PermissionGrantSource": (".loading", "PermissionGrantSource"),
    "InferenceOutput": (".pipeline", "InferenceOutput"),
    "MAX_MIGRATIONS": (".settings", "MAX_MIGRATIONS"),
    "MAX_NETWORK_COUNTER": (".network_collection", "MAX_NETWORK_COUNTER"),
    "MAX_NETWORK_LINKS": (".network_collection", "MAX_NETWORK_LINKS"),
    "MAX_PERIPHERAL_DEVICES": (".peripheral_collection", "MAX_PERIPHERAL_DEVICES"),
    "MAX_PERIPHERAL_ERROR_COUNT": (".peripheral_collection", "MAX_PERIPHERAL_ERROR_COUNT"),
    "MAX_PERIPHERAL_SOURCE_DEVICES": (".peripheral_collection", "MAX_PERIPHERAL_SOURCE_DEVICES"),
    "MAX_CALL_TIMEOUT_SECONDS": (".budgets", "MAX_CALL_TIMEOUT_SECONDS"),
    "MAX_CONCURRENCY_LIMIT": (".budgets", "MAX_CONCURRENCY_LIMIT"),
    "MAX_DESCRIPTORS_LIMIT": (".budgets", "MAX_DESCRIPTORS_LIMIT"),
    "MAX_MEMORY_BYTES_LIMIT": (".budgets", "MAX_MEMORY_BYTES_LIMIT"),
    "MAX_PROCESSES_LIMIT": (".budgets", "MAX_PROCESSES_LIMIT"),
    "MAX_PROCFS_PROCESSES": (".budgets", "MAX_PROCFS_PROCESSES"),
    "MAX_PLUGIN_ACTIVE_JOBS": (".telemetry", "MAX_PLUGIN_ACTIVE_JOBS"),
    "MAX_PLUGIN_QUEUE_DEPTH": (".telemetry", "MAX_PLUGIN_QUEUE_DEPTH"),
    "MAX_REDACTION_DEPTH": (".secrets", "MAX_REDACTION_DEPTH"),
    "MAX_REDACTION_NODES": (".secrets", "MAX_REDACTION_NODES"),
    "MAX_SECRET_FIELDS": (".secrets", "MAX_SECRET_FIELDS"),
    "MAX_SECRET_KEY_CHARS": (".secrets", "MAX_SECRET_KEY_CHARS"),
    "MAX_SECRET_PROVIDER_CHARS": (".secrets", "MAX_SECRET_PROVIDER_CHARS"),
    "MAX_SECRET_VALUE_BYTES": (".secrets", "MAX_SECRET_VALUE_BYTES"),
    "MAX_RESTARTS": (".supervisor_recovery", "MAX_RESTARTS"),
    "MAX_JOB_ID_CHARS": (".summaries", "MAX_JOB_ID_CHARS"),
    "MAX_PROTOCOL_CAPABILITIES": (".manifest_compatibility", "MAX_PROTOCOL_CAPABILITIES"),
    "MAX_PROTOCOL_CAPABILITY_CHARS": (".manifest_compatibility", "MAX_PROTOCOL_CAPABILITY_CHARS"),
    "MAX_DECLARED_PERMISSIONS": (".grants", "MAX_DECLARED_PERMISSIONS"),
    "MAX_DISTRIBUTION_FILES": (".discovery", "MAX_DISTRIBUTION_FILES"),
    "MAX_DISTRIBUTION_NAME_LENGTH": (".identity", "MAX_DISTRIBUTION_NAME_LENGTH"),
    "MAX_DISTRIBUTION_VERSION_LENGTH": (".identity", "MAX_DISTRIBUTION_VERSION_LENGTH"),
    "MAX_ENTRY_POINT_TARGET_LENGTH": (".identity", "MAX_ENTRY_POINT_TARGET_LENGTH"),
    "MAX_PLUGIN_CANDIDATES": (".discovery", "MAX_PLUGIN_CANDIDATES"),
    "MAX_SUPERVISED_WORKERS": (".supervisor_process", "MAX_SUPERVISED_WORKERS"),
    "MAX_SANDBOX_PATHS": (".sandbox", "MAX_SANDBOX_PATHS"),
    "MAX_TELEMETRY_COUNTER": (".telemetry", "MAX_TELEMETRY_COUNTER"),
    "MAX_TELEMETRY_DETAIL_CHARS": (".telemetry", "MAX_TELEMETRY_DETAIL_CHARS"),
    "MAX_TELEMETRY_PLUGINS": (".telemetry", "MAX_TELEMETRY_PLUGINS"),
    "MAX_TELEMETRY_TIMESTAMP_MS": (".telemetry", "MAX_TELEMETRY_TIMESTAMP_MS"),
    "MAX_WORKER_IMPORT_PATHS": (".loading", "MAX_WORKER_IMPORT_PATHS"),
    "MAX_WORKER_ARGUMENT_CHARS": (".supervisor_process", "MAX_WORKER_ARGUMENT_CHARS"),
    "MAX_WORKER_ARGUMENTS": (".supervisor_process", "MAX_WORKER_ARGUMENTS"),
    "MAX_ALERT_ID_CHARS": (".summaries", "MAX_ALERT_ID_CHARS"),
    "JsonObject": (".protocol", "JsonObject"),
    "JsonValue": (".protocol", "JsonValue"),
    "ManifestCompatibilityCode": (".manifest_compatibility", "ManifestCompatibilityCode"),
    "ManifestCompatibilityDecision": (".manifest_compatibility", "ManifestCompatibilityDecision"),
    "NETWORK_METADATA_PERMISSION": (".network_collection", "NETWORK_METADATA_PERMISSION"),
    "NETWORK_LINK_PERMISSION_PREFIX": (".network_collection", "NETWORK_LINK_PERMISSION_PREFIX"),
    "NETWORK_PERIPHERALS_PLUGIN_ID": (".network_collection", "NETWORK_PERIPHERALS_PLUGIN_ID"),
    "NetworkCollectionError": (".network_collection", "NetworkCollectionError"),
    "NetworkConnectivity": (".network_collection", "NetworkConnectivity"),
    "NetworkCounters": (".network_collection", "NetworkCounters"),
    "NetworkLinkKind": (".network_collection", "NetworkLinkKind"),
    "NetworkLinkSample": (".network_collection", "NetworkLinkSample"),
    "NetworkLinkState": (".network_collection", "NetworkLinkState"),
    "NetworkMetadataCollector": (".network_collection", "NetworkMetadataCollector"),
    "NetworkMetadataSource": (".network_collection", "NetworkMetadataSource"),
    "NetworkSnapshot": (".network_collection", "NetworkSnapshot"),
    "network_link_permission": (".network_collection", "network_link_permission"),
    "PERIPHERAL_DEVICE_PERMISSION_PREFIX": (
        ".peripheral_collection",
        "PERIPHERAL_DEVICE_PERMISSION_PREFIX",
    ),
    "PERIPHERAL_METADATA_PERMISSION": (".peripheral_collection", "PERIPHERAL_METADATA_PERMISSION"),
    "PeripheralBus": (".peripheral_collection", "PeripheralBus"),
    "PeripheralClass": (".peripheral_collection", "PeripheralClass"),
    "PeripheralCollectionError": (".peripheral_collection", "PeripheralCollectionError"),
    "PeripheralHealth": (".peripheral_collection", "PeripheralHealth"),
    "PeripheralMetadataCollector": (".peripheral_collection", "PeripheralMetadataCollector"),
    "PeripheralMetadataSource": (".peripheral_collection", "PeripheralMetadataSource"),
    "PeripheralSample": (".peripheral_collection", "PeripheralSample"),
    "PeripheralSnapshot": (".peripheral_collection", "PeripheralSnapshot"),
    "PluginContext": (".protocol", "PluginContext"),
    "PluginConfigurationSpec": (".settings", "PluginConfigurationSpec"),
    "PluginCatalog": (".identity", "PluginCatalog"),
    "PluginDiscoveryError": (".discovery", "PluginDiscoveryError"),
    "PluginHealth": (".protocol", "PluginHealth"),
    "PluginHealthStatus": (".protocol", "PluginHealthStatus"),
    "PluginLifecycle": (".protocol", "PluginLifecycle"),
    "PluginManifestCompatibilityGate": (
        ".manifest_compatibility",
        "PluginManifestCompatibilityGate",
    ),
    "PluginMetadata": (".discovery", "PluginMetadata"),
    "PluginProgress": (".protocol", "PluginProgress"),
    "PluginRejection": (".identity", "PluginRejection"),
    "PluginRejectionCode": (".identity", "PluginRejectionCode"),
    "PluginRequest": (".protocol", "PluginRequest"),
    "PluginResult": (".protocol", "PluginResult"),
    "PluginResultStatus": (".protocol", "PluginResultStatus"),
    "PluginSettings": (".settings", "PluginSettings"),
    "PluginSettingsError": (".settings", "PluginSettingsError"),
    "PluginSettingsStore": (".settings", "PluginSettingsStore"),
    "FilesystemSandbox": (".sandbox", "FilesystemSandbox"),
    "PluginSource": (".discovery", "PluginSource"),
    "PluginTelemetry": (".telemetry", "PluginTelemetry"),
    "PluginTelemetryHealth": (".telemetry", "PluginTelemetryHealth"),
    "PluginTelemetryRegistry": (".telemetry", "PluginTelemetryRegistry"),
    "PLUGIN_TELEMETRY_CONTRACT_VERSION": (".telemetry", "PLUGIN_TELEMETRY_CONTRACT_VERSION"),
    "PluginWorkerSupervisor": (".supervisor", "PluginWorkerSupervisor"),
    "PluginWorkerError": (".supervisor_session", "PluginWorkerError"),
    "ProcfsWorkerUsageProbe": (".budgets", "ProcfsWorkerUsageProbe"),
    "PipelineSnapshot": (".pipeline", "PipelineSnapshot"),
    "PipelinePolicyGate": (".policy", "PipelinePolicyGate"),
    "PipelineRunner": (".runner", "PipelineRunner"),
    "BoundedCollector": (".collection", "BoundedCollector"),
    "CollectionError": (".collection", "CollectionError"),
    "ReplaySource": (".collection", "ReplaySource"),
    "SourceSnapshot": (".collection", "SourceSnapshot"),
    "validated_allowlist": (".collection", "validated_allowlist"),
    "MAX_COLLECTED_ITEMS": (".collection", "MAX_COLLECTED_ITEMS"),
    "HardwareHealthCollector": (".hardware_collection", "HardwareHealthCollector"),
    "StorageIntelligenceCollector": (".storage_collection", "StorageIntelligenceCollector"),
    "ResourceSchedulerCollector": (".resource_collection", "ResourceSchedulerCollector"),
    "OptedInRootScanner": (".ingestion", "OptedInRootScanner"),
    "DocumentIngestor": (".document_ingestion", "DocumentIngestor"),
    "BuildMetadataIngestor": (".build_ingestion", "BuildMetadataIngestor"),
    "BuildRecord": (".build_ingestion", "BuildRecord"),
    "BuildOutcome": (".build_ingestion", "BuildOutcome"),
    "RepositoryProfile": (".build_ingestion", "RepositoryProfile"),
    "build_record_error": (".build_ingestion", "build_record_error"),
    "BUILD_METADATA_PERMISSION": (".build_ingestion", "BUILD_METADATA_PERMISSION"),
    "DesktopContextCollector": (".desktop_collection", "DesktopContextCollector"),
    "DesktopSession": (".desktop_collection", "DesktopSession"),
    "WindowSample": (".desktop_collection", "WindowSample"),
    "WindowRole": (".desktop_collection", "WindowRole"),
    "WindowState": (".desktop_collection", "WindowState"),
    "window_identity": (".desktop_collection", "window_identity"),
    "window_sample_error": (".desktop_collection", "window_sample_error"),
    "DESKTOP_CONSENT_PERMISSION": (".desktop_collection", "DESKTOP_CONSENT_PERMISSION"),
    "DESKTOP_METADATA_PERMISSION": (".desktop_collection", "DESKTOP_METADATA_PERMISSION"),
    "DocumentCandidate": (".document_ingestion", "DocumentCandidate"),
    "DocumentScan": (".document_ingestion", "DocumentScan"),
    "DocumentRejection": (".document_ingestion", "DocumentRejection"),
    "RefusedDocument": (".document_ingestion", "RefusedDocument"),
    "detect_document_type": (".document_ingestion", "detect_document_type"),
    "container_depth": (".document_ingestion", "container_depth"),
    "IngestedFile": (".ingestion", "IngestedFile"),
    "IngestionScan": (".ingestion", "IngestionScan"),
    "IngestionError": (".ingestion", "IngestionError"),
    "IngestionRejection": (".ingestion", "IngestionRejection"),
    "RejectedFile": (".ingestion", "RejectedFile"),
    "ResourceSample": (".resource_collection", "ResourceSample"),
    "ResourceScope": (".resource_collection", "ResourceScope"),
    "PressureStall": (".resource_collection", "PressureStall"),
    "UnitState": (".resource_collection", "UnitState"),
    "resource_sample_error": (".resource_collection", "resource_sample_error"),
    "resource_unit_permission": (".resource_collection", "resource_unit_permission"),
    "RESOURCE_METADATA_PERMISSION": (".resource_collection", "RESOURCE_METADATA_PERMISSION"),
    "StorageSample": (".storage_collection", "StorageSample"),
    "StorageCounters": (".storage_collection", "StorageCounters"),
    "StorageBus": (".storage_collection", "StorageBus"),
    "StorageHealth": (".storage_collection", "StorageHealth"),
    "storage_device_permission": (".storage_collection", "storage_device_permission"),
    "storage_sample_error": (".storage_collection", "storage_sample_error"),
    "STORAGE_METADATA_PERMISSION": (".storage_collection", "STORAGE_METADATA_PERMISSION"),
    "HardwareSample": (".hardware_collection", "HardwareSample"),
    "SensorHealth": (".hardware_collection", "SensorHealth"),
    "SensorKind": (".hardware_collection", "SensorKind"),
    "hardware_sample_error": (".hardware_collection", "hardware_sample_error"),
    "hardware_sensor_permission": (".hardware_collection", "hardware_sensor_permission"),
    "HARDWARE_METADATA_PERMISSION": (".hardware_collection", "HARDWARE_METADATA_PERMISSION"),
    "JobResultStore": (".job_results", "JobResultStore"),
    "JobRecord": (".job_results", "JobRecord"),
    "JobResultError": (".job_results", "JobResultError"),
    "STAGE_ORDER": (".runner", "STAGE_ORDER"),
    "PluginFlowController": (".flow", "PluginFlowController"),
    "JobCancellationRegistry": (".cancellation", "JobCancellationRegistry"),
    "JobCancellationToken": (".cancellation", "JobCancellationToken"),
    "JobCancelledError": (".cancellation", "JobCancelledError"),
    "Cancellation": (".cancellation", "Cancellation"),
    "CancellationReason": (".cancellation", "CancellationReason"),
    "FlowRefusal": (".flow", "FlowRefusal"),
    "FlowRefusedError": (".flow", "FlowRefusedError"),
    "FlowSnapshot": (".flow", "FlowSnapshot"),
    "PolicyDecision": (".policy", "PolicyDecision"),
    "PolicyRefusal": (".policy", "PolicyRefusal"),
    "PolicyRefusedError": (".policy", "PolicyRefusedError"),
    "ADMITTED": (".policy", "ADMITTED"),
    "PipelineStage": (".pipeline", "PipelineStage"),
    "PipelineStateMachine": (".pipeline", "PipelineStateMachine"),
    "PipelineTransitionError": (".pipeline", "PipelineTransitionError"),
    "PLUGIN_ENTRY_POINT_GROUP": (".discovery", "PLUGIN_ENTRY_POINT_GROUP"),
    "PLUGIN_MANIFEST_FILENAME": (".discovery", "PLUGIN_MANIFEST_FILENAME"),
    "PostprocessedOutput": (".pipeline", "PostprocessedOutput"),
    "PreprocessedOutput": (".pipeline", "PreprocessedOutput"),
    "ProgressReporter": (".protocol", "ProgressReporter"),
    "ScaledProgressReporter": (".protocol", "ScaledProgressReporter"),
    "ReplayNetworkMetadataSource": (".network_collection", "ReplayNetworkMetadataSource"),
    "ReplayPeripheralMetadataSource": (".peripheral_collection", "ReplayPeripheralMetadataSource"),
    "ResolvedPlugin": (".identity", "ResolvedPlugin"),
    "ResolvedOutput": (".pipeline", "ResolvedOutput"),
    "ResolvedConfiguration": (".secrets", "ResolvedConfiguration"),
    "ResultSummary": (".summaries", "ResultSummary"),
    "ResultSummaryRegistry": (".summaries", "ResultSummaryRegistry"),
    "REDACTED": (".secrets", "REDACTED"),
    "REDACTION_LIMIT": (".secrets", "REDACTION_LIMIT"),
    "SECRET_REFERENCE_FIELD": (".secrets", "SECRET_REFERENCE_FIELD"),
    "SECRET_SCHEMA_MARKER": (".secrets", "SECRET_SCHEMA_MARKER"),
    "SETTINGS_DOCUMENT_VERSION": (".settings", "SETTINGS_DOCUMENT_VERSION"),
    "StageOutput": (".pipeline", "StageOutput"),
    "TensorContract": (".artifact_compatibility", "TensorContract"),
    "TensorSpec": (".artifact_compatibility", "TensorSpec"),
    "SourceStatus": (".triggers", "SourceStatus"),
    "SummaryError": (".summaries", "SummaryError"),
    "SummarySeverity": (".summaries", "SummarySeverity"),
    "SecretConfigurationError": (".secrets", "SecretConfigurationError"),
    "SecretProvider": (".secrets", "SecretProvider"),
    "SecretRedactor": (".secrets", "SecretRedactor"),
    "SecretReference": (".secrets", "SecretReference"),
    "SandboxPolicyError": (".sandbox", "SandboxPolicyError"),
    "SecretResolutionError": (".secrets", "SecretResolutionError"),
    "Trigger": (".triggers", "Trigger"),
    "TriggerCoordinator": (".triggers", "TriggerCoordinator"),
    "TriggerDisposition": (".triggers", "TriggerDisposition"),
    "TriggerKind": (".triggers", "TriggerKind"),
    "TriggerReceipt": (".triggers", "TriggerReceipt"),
    "TriggerValidationError": (".triggers", "TriggerValidationError"),
    "TextRedactor": (".summaries", "TextRedactor"),
    "WARNING_RISK_MAX": (".summaries", "WARNING_RISK_MAX"),
    "WorkloadPlugin": (".protocol", "WorkloadPlugin"),
    "WorkerMessageType": (".ipc", "WorkerMessageType"),
    "WorkerBudgetCode": (".budgets", "WorkerBudgetCode"),
    "WorkerBudgetEnforcer": (".budgets", "WorkerBudgetEnforcer"),
    "WorkerBudgetExceededError": (".budgets", "WorkerBudgetExceededError"),
    "WorkerBudgetLimits": (".budgets", "WorkerBudgetLimits"),
    "WorkerBudgetSnapshot": (".budgets", "WorkerBudgetSnapshot"),
    "WorkerDiagnostic": (".supervisor_diagnostics", "WorkerDiagnostic"),
    "WorkerDiagnosticCode": (".supervisor_diagnostics", "WorkerDiagnosticCode"),
    "WorkerFailureObserver": (".supervisor_recovery", "WorkerFailureObserver"),
    "WorkerLauncher": (".supervisor_process", "WorkerLauncher"),
    "WorkerProcess": (".supervisor_process", "WorkerProcess"),
    "WorkerRecoveryPolicy": (".supervisor_recovery", "WorkerRecoveryPolicy"),
    "WorkerSpec": (".supervisor_process", "WorkerSpec"),
    "WorkerState": (".supervisor_diagnostics", "WorkerState"),
    "WorkerStatus": (".supervisor_diagnostics", "WorkerStatus"),
    "WorkerResourceUsage": (".budgets", "WorkerResourceUsage"),
    "BWRAP_PATH": (".sandbox", "BWRAP_PATH"),
    "artifact_filename": (".artifacts", "artifact_filename"),
    "artifact_provenance_document": (".artifact_trust", "artifact_provenance_document"),
    "artifact_reference_document": (".artifact_installation", "artifact_reference_document"),
    "artifact_reference_error": (".artifacts", "artifact_reference_error"),
    "artifact_reference_from_document": (
        ".artifact_installation",
        "artifact_reference_from_document",
    ),
    "artifact_signature_payload": (".artifact_trust", "artifact_signature_payload"),
    "adapt_bundled_manifest_v1": (".manifest_compatibility", "adapt_bundled_manifest_v1"),
    "decode_frame": (".ipc", "decode_frame"),
    "discover_plugin_metadata": (".discovery", "discover_plugin_metadata"),
    "encode_frame": (".ipc", "encode_frame"),
    "execute_frame": (".ipc", "execute_frame"),
    "entry_points_from_distributions": (".loading", "entry_points_from_distributions"),
    "external_worker_specs": (".loading", "external_worker_specs"),
    "await_worker_ready": (".ipc", "await_worker_ready"),
    "handshake_frame": (".ipc", "handshake_frame"),
    "negotiate_handshake": (".ipc", "negotiate_handshake"),
    "network_snapshot_error": (".network_collection", "network_snapshot_error"),
    "peripheral_device_permission": (".peripheral_collection", "peripheral_device_permission"),
    "peripheral_snapshot_error": (".peripheral_collection", "peripheral_snapshot_error"),
    "resolve_plugin_identities": (".identity", "resolve_plugin_identities"),
    "resolve_plugin_compatibility": (".manifest_compatibility", "resolve_plugin_compatibility"),
    "parse_handshake": (".ipc", "parse_handshake"),
    "parse_execute": (".ipc", "parse_execute"),
    "parse_progress": (".ipc", "parse_progress"),
    "parse_ready": (".ipc", "parse_ready"),
    "parse_result": (".ipc", "parse_result"),
    "progress_frame": (".ipc", "progress_frame"),
    "ready_frame": (".ipc", "ready_frame"),
    "result_frame": (".ipc", "result_frame"),
    "result_frames": (".ipc", "result_frames"),
    "parse_result_chunk": (".ipc", "parse_result_chunk"),
    "assemble_result_chunks": (".ipc", "assemble_result_chunks"),
    "perform_service_handshake": (".ipc", "perform_service_handshake"),
    "parse_secret_reference": (".secrets", "parse_secret_reference"),
    "resolve_configuration": (".secrets", "resolve_configuration"),
    "secret_paths": (".secrets", "secret_paths"),
    "severity_for_risk": (".summaries", "severity_for_risk"),
    "validate_secret_references": (".secrets", "validate_secret_references"),
    "perform_worker_handshake": (".ipc", "perform_worker_handshake"),
    "read_frame": (".ipc", "read_frame"),
    "write_frame": (".ipc", "write_frame"),
    "KernelAggregate": (".kernel_telemetry", "KernelAggregate"),
    "KernelTelemetryError": (".kernel_telemetry", "KernelTelemetryError"),
    "KernelTelemetryState": (".kernel_telemetry", "KernelTelemetryState"),
    "LatencyHistogram": (".kernel_telemetry", "LatencyHistogram"),
    "KernelCounter": (".kernel_telemetry", "KernelCounter"),
    "UnixSocketAggregateSource": (".kernel_telemetry", "UnixSocketAggregateSource"),
    "AbsentAggregateSource": (".kernel_telemetry", "AbsentAggregateSource"),
    "KernelAggregateSource": (".kernel_telemetry", "KernelAggregateSource"),
    "parse_aggregate": (".kernel_telemetry", "parse_aggregate"),
    "scheduler_features": (".kernel_telemetry", "scheduler_features"),
}

__all__ = list(_EXPORTS)
_RESOLUTION_STATE = _local()


def __getattr__(name: str) -> object:
    """Resolve and cache one declared export without eagerly loading its peers."""
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    resolving = getattr(_RESOLUTION_STATE, "names", None)
    if resolving is None:
        resolving = set()
        _RESOLUTION_STATE.names = resolving
    if name in resolving:
        raise AttributeError(f"module {__name__!r} cannot resolve {name!r} recursively")

    resolving.add(name)
    try:
        module_name, attribute_name = target
        module = _import_module(module_name, __name__)
        value = getattr(module, attribute_name)
    finally:
        resolving.remove(name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """List lazy public exports without resolving them."""
    return sorted(set(globals()) | set(__all__))
